Add Cypress

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -60,3 +60,16 @@ if [ -n "$SCSS_LINT_COMMAND" ]; then
         exit 1
     fi
 fi
+
+if [ -n "$CYPRESS_COMMAND" ]; then
+    CYPRESS_OUTPUT=$($CYPRESS_COMMAND)
+    CYPRESS_RETVAL=$?
+
+    if [ $CYPRESS_RETVAL -ne 0 ]; then
+        echo "======================================="
+	    echo "              CYPRESS Errors           "
+	    echo "======================================="
+        echo "$CYPRESS_OUTPUT"
+        exit 1
+    fi
+fi
