Add phpunit

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -35,6 +35,19 @@ if [ -n "$PHPMD_COMMAND" ]; then
     fi
 fi
 
+if [ -n "$PHPUNIT_COMMAND" ]; then
+    PHPUNIT_OUTPUT=$($PHPUNIT_COMMAND)
+    PHPUNIT_RETVAL=$?
+
+    if [ $PHPUNIT_RETVAL -ne 0 ]; then
+        echo "======================================="
+	    echo "            PHPUNIT Errors             "
+	    echo "======================================="
+        echo "$PHPUNIT_OUTPUT"
+        exit 1
+    fi
+fi
+
 if [ -n "$SCSS_LINT_COMMAND" ]; then
     SCSS_LINT_OUTPUT=$($SCSS_LINT_COMMAND)
     SCSS_LINT_RETVAL=$?
